# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 241328fa37810973c9550a849dd7a5e4404c6295f8c9e3ba67c905071d81a62744b03bab68f0da002f1a504bf9a544d6e5c69fedfd68566634af3f02c76a9f6d

test:
  secret_key_base: f36821dbd4707b24b085b498b31c7a7d92a7e2e4775f3a5c31df88e601672dea2a06ad76573bc8a7e3f8c169c8acc26e2c137cb2c997e068854e89bd97c704d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
